name: CI
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
          # Set installed toolchain as default
          default: nightly
      
      - name: Build WASM
        run: |
          sh ./build_rs.sh
          cd ./frontend

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build
          
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          # Build directory to deploy
          build_dir: ./dist
          committer: SnowballSH
          author: SnowballSH
          
