name: CI
on: [push]
jobs:
  build:
    name: Build Webpage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          # Build directory to deploy
          build_dir: ./frontend/dist
          committer: SnowballSH
          author: SnowballSH
          
